import { MyChakraProvider } from '@/components/MyChakraProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StoreProvider } from '@/components/StoreProvider'
import SiteHeader from '@/components/SiteHeader'
import { Grid, GridItem, Box } from '@chakra-ui/layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'IPF Compass',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <MyChakraProvider>
            <Grid gridTemplateRows="80px 1fr" style={{ height: '100vh' }}>
              <GridItem>
                <SiteHeader />
              </GridItem>
              <GridItem>{children}</GridItem>
            </Grid>
          </MyChakraProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
